name: Acceptance Test Trigger

on:
  issue_comment:
    types: [created]

jobs:
  testacc-trigger:
    name: Trigger Acceptance Tests
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/testacc')
    steps:
      - name: Dispatch testacc command
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.TRIGGER_TOKEN }}
          commands: testacc
          permission: write
          issue-type: pull-request
